version: "2"

services:
  nfacctd:
    image: pmacct/nfacctd:v1.7.9
    restart: always
    ports:
      - "9996:9996/udp"
    volumes:
      - ./nfacctd/nfacctd.conf:/etc/pmacct/nfacctd.conf
      - ./nfacctd/pretag.map:/etc/pmacct/pretag.map
      - ./nfacctd/kafka.csv:/etc/pmacct/kafka.csv

  kafka:
    image: 'bitnami/kafka:3.8.0'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - XPACK_MONITORING_ENABLED=false
