services:
  nfacctd:
    image: pmacct/nfacctd:latest
    restart: always
    platform: linux/x86_64
    ports:
      - "9996:9996/udp"
    volumes:
      - ./conf/nfacctd.conf:/etc/pmacct/nfacctd.conf
      - ./conf/pretag.map:/etc/pmacct/pretag.map
      - ./conf/kafka.csv:/etc/pmacct/kafka.csv

  kafka:
    image: 'bitnami/kafka:latest'
    platform: linux/x86_64
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.1
    volumes:
      - ./conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./output:/usr/share/logstash/output
    environment:
      - XPACK_MONITORING_ENABLED=false
