services:
  nfacctd:
    image: pmacct/nfacctd:v1.7.9
    profiles:
      - collector
    restart: always
    network_mode: host
    ports:
      - "9996:9996/udp"
    volumes:
      - ./nfacctd/nfacctd.conf:/etc/pmacct/nfacctd.conf
      - ./nfacctd/ipfix.primitives.lst:/etc/pmacct/ipfix.primitives.lst
      - ./nfacctd/pretag.map:/etc/pmacct/pretag.map
      - ./nfacctd/ports.lst:/etc/pmacct/ports.lst
      - ./nfacctd/kafka.csv:/etc/pmacct/kafka.csv

  kafka:
    image: 'bitnami/kafka:3.8.0'
    profiles:
      - collector
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-config:
    image: 'bitnami/kafka:3.8.0'
    profiles:
      - collector
    depends_on:
      - kafka
    environment:
      - MN_KAFKA_RENTENTION_MS=${MN_KAFKA_RENTENTION_MS}
      - MN_KAFKA_RENTENTION_BYTES=${MN_KAFKA_RENTENTION_BYTES}
    volumes:
      - ./kafka_config:/app
    command: ["bash", "/app/config.sh"]

  pipeline_flow_5m_asn_app:
    image: docker.elastic.co/logstash/logstash:8.15.2
    restart: always
    profiles:
      - collector
    volumes:
      - ./pipeline-flow-5m-asn-app/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./pipeline-flow-5m-asn-app/data/:/var/lib/metranova/:ro
    environment:
      - XPACK_MONITORING_ENABLED=false
      - LOGSTASH_OPENSEARCH_PASSWORD=${MN_LOGSTASH_OPENSEARCH_PASSWORD}
      - LOGSTASH_OPENSEARCH_USER=metranova_writer
      - OPENSEARCH_URL=${MN_OPENSEARCH_URL}
    #TODO: We need to install the opensearch output plugin before starting logstash. Should make this a custom image.
    command: bash -c "logstash-plugin install logstash-output-opensearch && /usr/local/bin/docker-entrypoint"

  opensearch: 
    image: opensearchproject/opensearch:2.17.1
    profiles:
      - archive
    restart: always
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch # Name the node that will run in this container
      - discovery.seed_hosts=opensearch # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - plugins.security.unsupported.restapi.allow_securityconfig_modification=true # allow us to enable anonymous access auth
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${MN_OPENSEARCH_ADMIN_PASSWORD} # Sets admin password. Must be a strong password or opensearch will reject.
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.1
    profiles:
      - archive
    restart: always
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      SERVER_BASEPATH: ${MN_OPENSEARCHDASH_BASEPATH} # Set the base path for OpenSearch Dashboards
      SERVER_REWRITEBASEPATH: true
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query

  opensearch-config:
    image: metranova/opensearch-config:latest
    profiles:
      - archive
    build:
      context: ./opensearch_config
      dockerfile: Dockerfile
    command: ["bash", "config.sh"]
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_ADMIN_PASSWORD=${MN_OPENSEARCH_ADMIN_PASSWORD}
      - LOGSTASH_OPENSEARCH_PASSWORD=${MN_LOGSTASH_OPENSEARCH_PASSWORD}

  grafana:
    image: grafana/grafana:11.2.2-ubuntu
    profiles:
      - frontend
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource,grafana-googlesheets-datasource,grafana-polystat-panel,marcusolsson-hourly-heatmap-panel,netsage-sankey-panel,netsage-slopegraph-panel,esnet-chord-panel,netsage-bumpchart-panel,esnet-matrix-panel,grafana-clickhouse-datasource,esnet-arcdiagram-panel,esnet-networkmap-panel
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SECURITY_ADMIN_PASSWORD=${MN_GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - OPENSEARCH_URL=${MN_OPENSEARCH_URL}
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/images/metranova_icon.svg:/usr/share/grafana/public/img/grafana_icon.svg

  nginx-cert-init:
    image: certbot/certbot
    profiles:
      - archive
      - frontend
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/selfsigned.sh:/usr/share/metranova/selfsigned.sh
    environment:
      - MN_HOSTNAME=${MN_HOSTNAME}
    entrypoint: "/bin/sh /usr/share/metranova/selfsigned.sh"

  psregister:
    image: metranova/psregister:latest
    profiles:
      - archive
    build:
      context: ./psregister
      dockerfile: Dockerfile
    environment:
      - LOOKUP_SERVICE_URL=${MN_LOOKUP_SERVICE_URL}
      - HOSTNAME=${MN_HOSTNAME}
      - ARCHIVE_URL=${MN_PUBLIC_OPENSEARCH_URL}

  grafana_agent:
    image: metranova/grafana_agent:latest
    profiles:
      - frontend
    restart: always
    build:
      context: ./grafana_agent
      dockerfile: Dockerfile
    environment:
      - CHECK_INTERVAL=${MN_GRAFANA_AGENT_CHECK_INTERVAL}
      - LOOKUP_SERVICE_ES_URL=${MN_LOOKUP_SERVICE_ES_URL}
      - LOOKUP_SERVICE_ES_INDEX=${MN_LOOKUP_SERVICE_ES_INDEX}
      - LOOKUP_SERVICE_ES_USER=${MN_LOOKUP_SERVICE_ES_USER}
      - LOOKUP_SERVICE_ES_PASS=${MN_LOOKUP_SERVICE_ES_PASS}
      - GRAFANA_URL=${MN_GRAFANA_URL}
      - GRAFANA_USER=${MN_GRAFANA_USER}
      - GRAFANA_PASSWORD=${MN_GRAFANA_PASSWORD}

  nginx:
    image: nginx:1.27-alpine
    profiles:
      - archive
      - frontend
    restart: always
    depends_on:
      - nginx-cert-init
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - MN_HOSTNAME=${MN_HOSTNAME}

####
# The following is some patchwork Andy started to get a LetsEncrypt certbot container working. It's not finished yet.
#
# Th following goes under nginx and should reload the certs every 6 hours. 
# There is a problem where overriding the command prevents templates from being run through envsubst. 
# Probably just a matter of getting the right command.
    #reloads certs periodically
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

# The following is the start of a certbot container. 
  # certbot:
  #   image: certbot/certbot
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/entrypoint.sh:/usr/share/metranova/entrypoint.sh
  #   environment:
  #     - MN_HOSTNAME=${MN_HOSTNAME}
  #     - MN_USE_LETSENCRYPT=${MN_USE_LETSENCRYPT}
  #   entrypoint: "/bin/bash /usr/share/metranova/entrypoint.sh"

volumes:
  opensearch-data:
